### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Leo-zhanglj** [a-p-z/gitstats#1]
hi,
I get some error below

INFO:root:executing git ls-files
INFO:root:git blame
INFO:root:blaming   0%
INFO:root:blaming  10%
INFO:root:blaming  20%
INFO:root:blaming  30%
INFO:root:blaming  40%
INFO:root:blaming  50%
INFO:root:blaming  60%
INFO:root:blaming  70%
INFO:root:blaming  80%
INFO:root:blaming  90%
INFO:root:blaming 100%
INFO:root:counting commits over month by author
INFO:root:calculating impacts over month
INFO:root:counting commits over month by author
INFO:root:counting commits and impacts by author
INFO:root:executing git shortlog HEAD -s -e -n --no-merges
INFO:root:counting commits by author
INFO:root:counting commits and on behalf of
Traceback (most recent call last):
  File "D:\gitstats\gitstats.py", line 36, in <module>
    printer.print(numstat, blame)
  File "D:\gitstats\printer\printer.py", line 45, in print
    self.__print_commits_by_committer(numstat)
  File "D:\gitstats\printer\printer.py", line 277, in __print_commits_by_committer
    total = sum_by_row(data)
  File "D:\gitstats\core\utilities.py", line 22, in sum_by_row
    total = [0] * len(table[0])
IndexError: list index out of range

env: Python 3.7.9 windows x86-64

**Comment by andreRibeiro1989** [comment]
same for me

**Comment by a-p-z** [comment]
fixed
