### ISSUE TITLE
% changes and impact

### ISSUE THREAD

**Issue by tiagaoalb** [a-p-z/gitstats#4]
Hi @a-p-z, how u doing?

Could you elaborate what is `% of changes` and `impact` are?
I need to understand because I would like to create subtitles.

**Comment by a-p-z** [comment]
% of changes
a change is an insertion or a deletion
% of changes is the percentage of change made by an author over the total changes in the repository.
It represent how much an author has contributed to the project.
https://github.com/a-p-z/gitstats/blob/master/core/utilities.py#L56


impact/commit
impact/commit is a value which represent, in mean, how much commits by an author are impacting. In theory commits with a high impact are risky and small commits, with a small impact, are to prefer.
https://github.com/a-p-z/gitstats/blob/master/core/utilities.py#L75

**Comment by tiagaoalb** [comment]
> % of changes a change is an insertion or a deletion % of changes is the percentage of change made by an author over the total changes in the repository. It represent how much an author has contributed to the project. https://github.com/a-p-z/gitstats/blob/master/core/utilities.py#L56
> 
> impact/commit impact/commit is a value which represent, in mean, how much commits by an author are impacting. In theory commits with a high impact are risky and small commits, with a small impact, are to prefer. https://github.com/a-p-z/gitstats/blob/master/core/utilities.py#L75

Thank you very much!
