### ISSUE TITLE
Markup file

### ISSUE THREAD

**Issue by joaopauloaramuni** [a-p-z/gitstats#5]
Hi, confluence no longer supports markup files. Do you know how we can bring this file to the new confluence editor?

**Comment by a-p-z** [comment]
Hi,
where have you read that?

**Comment by chargui-yassine** [comment]
https://support.atlassian.com/confluence-cloud/docs/insert-confluence-wiki-markup/
Note: the new editor doesn’t support markup. Learn more about [the new editor roadmap](https://support.atlassian.com/confluence-cloud/docs/confluence-cloud-editor-roadmap/).

**Comment by a-p-z** [comment]
Thanks for the reference.
As far as I understand it is only the editor which will not support the markup anymore.
The api should continue to support it
